# see https://github.com/mapbender/owsproxy3/blob/master/CONFIGURATION.md#extension-configuration
ows_proxy3_core:
    logging: '%ows_proxy3_logging%'
    obfuscate_client_ip: '%ows_proxy3_obfuscate_client_ip%'
    proxy:
        host: '%ows_proxy3_host%'
        port: '%ows_proxy3_port%'
        connecttimeout: '%ows_proxy3_connecttimeout%'
        timeout: '%ows_proxy3_timeout%'
        user: '%ows_proxy3_user%'
        password: '%ows_proxy3_password%'
        checkssl: true
        noproxy: '%ows_proxy3_noproxy%'
